# Generated by Django 5.0.6 on 2025-12-10 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('generated', 'Générée'), ('deployed', 'Déployée'), ('error', 'Erreur'), ('archived', 'Archivée')], default='draft', max_length=20, verbose_name='Statut')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='Version')),
                ('api_base_url', models.URLField(blank=True, verbose_name="URL de base de l'API")),
                ('admin_url', models.URLField(blank=True, verbose_name="URL d'administration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier déploiement')),
                ('deployment_target', models.CharField(choices=[('local', 'Local'), ('staging', 'Environnement de test'), ('production', 'Production')], default='local', max_length=100, verbose_name='Environnement de déploiement')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration technique')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_app', to='studio.project', verbose_name='Projet associé')),
            ],
            options={
                'verbose_name': 'Application générée',
                'verbose_name_plural': 'Applications générées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('rolled_back', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('log_output', models.TextField(blank=True, verbose_name='Sortie du journal')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_logs', to='runtime.generatedapp', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Journal de déploiement',
                'verbose_name_plural': 'Journaux de déploiement',
                'ordering': ['-started_at'],
            },
        ),
    ]
