# Generated by Django 5.0.6 on 2025-11-14 03:04

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public unique utilisé dans les URLs et APIs', unique=True, verbose_name='Tracking ID')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=20, verbose_name='Rôle')),
                ('email', models.EmailField(help_text="L'adresse email est utilisée comme identifiant de connexion.", max_length=254, unique=True, verbose_name='Adresse email')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('numero_telephone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres.', regex='^\\+?\\d{8,15}$')], verbose_name='Numéro de téléphone')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'foundation_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="ID de l'événement")),
                ('event_name', models.CharField(db_index=True, max_length=255, verbose_name="Nom de l'événement")),
                ('event_data', models.JSONField(default=dict, verbose_name="Données de l'événement")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('PROCESSED', 'Traité'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('source_module', models.CharField(blank=True, max_length=100, verbose_name='Module source')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'foundation_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public unique utilisé dans les URLs et APIs', unique=True, verbose_name='Tracking ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'organisation")),
                ('type', models.CharField(choices=[('PERSONAL', 'Personnel'), ('BUSINESS', 'Entreprise')], default='PERSONAL', max_length=20, verbose_name="Type d'organisation")),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspendue')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('city', models.CharField(blank=True, help_text="Ville où est basée l'organisation", max_length=100, null=True, verbose_name='Ville')),
                ('numero_certification', models.CharField(blank=True, help_text='Numéro SIRET, KBIS ou autre certification officielle', max_length=255, null=True, verbose_name='Numéro de certification')),
                ('is_active', models.BooleanField(default=False, help_text="Les organisations doivent être validées avant d'être activées", verbose_name='Organisation active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Organisation vérifiée')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('max_members', models.PositiveIntegerField(default=5, help_text="Limite définie par l'abonnement", verbose_name='Nombre maximum de membres')),
                ('max_projects', models.PositiveIntegerField(default=3, help_text="Limite définie par l'abonnement", verbose_name='Nombre maximum de projets')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'foundation_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public unique utilisé dans les URLs et APIs', unique=True, verbose_name='Tracking ID')),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('ADMIN', 'Administrateur'), ('MEMBER', 'Membre')], default='MEMBER', max_length=20, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('PENDING', 'En attente')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Rejoint le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='foundation.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre d'organisation",
                'verbose_name_plural': "Membres d'organisation",
                'db_table': 'foundation_organization_member',
                'ordering': ['organization', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='TypeAbonnement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public unique utilisé dans les URLs et APIs', unique=True, verbose_name='Tracking ID')),
                ('nom', models.CharField(choices=[('FREE', 'Gratuit'), ('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], max_length=50, verbose_name='Nom du plan')),
                ('categorie_utilisateur', models.CharField(choices=[('CLIENT', 'Client'), ('ORGANIZATION', 'Organisation')], max_length=50, verbose_name="Catégorie d'utilisateur")),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarif (FCFA)')),
                ('duree_en_jours', models.PositiveIntegerField(verbose_name='Durée en jours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce plan peut être souscrit', verbose_name='Plan actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Type d'abonnement",
                'verbose_name_plural': "Types d'abonnement",
                'db_table': 'foundation_type_abonnement',
                'ordering': ['tarif'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public unique utilisé dans les URLs et APIs', unique=True, verbose_name='Tracking ID')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('transaction_reference', models.CharField(blank=True, help_text='Référence de la transaction de paiement (API bancaire)', max_length=255, null=True, verbose_name='Référence de transaction')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant réellement payé pour cet abonnement', max_digits=10, verbose_name='Montant payé')),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('user', models.ForeignKey(help_text="Utilisateur souscripteur (propriétaire de l'organisation)", on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('type_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='foundation.typeabonnement', verbose_name="Type d'abonnement")),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'foundation_abonnement',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tracking_id'], name='foundation__trackin_902313_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='foundation__email_cf5b94_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_name', 'status'], name='foundation__event_n_bb3033_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='foundation__created_5f3572_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='typeabonnement',
            unique_together={('nom', 'categorie_utilisateur')},
        ),
    ]
