# Generated by Django 5.0.6 on 2025-11-27 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_event'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres.', regex='^\\+?\\d{8,15}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
