# Generated by Django 5.0.6 on 2025-11-20 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0002_remove_user_role_delete_event'),
        ('studio', '0003_alter_component_category_alter_component_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'intégration")),
                ('integration_type', models.CharField(choices=[('email', 'Email (SMTP/SendGrid)'), ('stripe', 'Stripe'), ('webhook', 'Webhook HTTP'), ('database', 'Base de données'), ('storage', 'Stockage (S3, etc.)'), ('notification', 'Notifications (SMS, Push)'), ('api', 'API REST personnalisée'), ('slack', 'Slack'), ('zapier', 'Zapier'), ('custom', 'Personnalisée')], max_length=50, verbose_name="Type d'intégration")),
                ('config', models.JSONField(default=dict, help_text="Configuration générale de l'intégration", verbose_name='Configuration')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Erreur'), ('testing', 'En test')], default='inactive', max_length=20, verbose_name='Statut')),
                ('total_calls', models.IntegerField(default=0, verbose_name='Appels totaux')),
                ('successful_calls', models.IntegerField(default=0, verbose_name='Appels réussis')),
                ('failed_calls', models.IntegerField(default=0, verbose_name='Appels échoués')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('rate_limit', models.IntegerField(default=100, help_text='Nombre maximum de requêtes par heure', verbose_name='Limite de requêtes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='foundation.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Intégration',
                'verbose_name_plural': 'Intégrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(help_text='api_key, oauth_token, username_password, etc.', max_length=50, verbose_name='Type de credential')),
                ('encrypted_data', models.BinaryField(verbose_name='Données encryptées')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Pour les tokens avec expiration', null=True, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='automation.integration', verbose_name='Intégration')),
            ],
            options={
                'verbose_name': "Credential d'intégration",
                'verbose_name_plural': "Credentials d'intégration",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du workflow')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('PAUSED', 'En pause'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('config', models.JSONField(default=dict, help_text='Configuration générale du workflow', verbose_name='Configuration')),
                ('variables', models.JSONField(default=dict, help_text='Variables globales du workflow', verbose_name='Variables')),
                ('execution_count', models.IntegerField(default=0, verbose_name="Nombre d'exécutions")),
                ('success_count', models.IntegerField(default=0, verbose_name='Exécutions réussies')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Exécutions échouées')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='foundation.organization', verbose_name='Organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='studio.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manuel'), ('event', 'Événement système'), ('webhook', 'Webhook'), ('schedule', 'Planification (cron)'), ('form_submit', 'Soumission de formulaire'), ('data_change', 'Modification de données'), ('api_call', 'Appel API')], max_length=50, verbose_name='Type de déclencheur')),
                ('config', models.JSONField(default=dict, help_text='Configuration spécifique au type de déclencheur', verbose_name='Configuration')),
                ('webhook_url', models.CharField(blank=True, help_text='URL générée automatiquement pour recevoir les webhooks', max_length=500, verbose_name='URL du webhook')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Secret du webhook')),
                ('cron_expression', models.CharField(blank=True, help_text='Expression cron pour la planification (ex: 0 9 * * *)', max_length=100, verbose_name='Expression cron')),
                ('event_type', models.CharField(blank=True, help_text="Type d'événement à écouter (ex: project.created)", max_length=100, verbose_name="Type d'événement")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='automation.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Déclencheur',
                'verbose_name_plural': 'Déclencheurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('input_data', models.JSONField(default=dict, help_text='Données fournies au démarrage du workflow', verbose_name="Données d'entrée")),
                ('output_data', models.JSONField(blank=True, default=dict, help_text="Résultat de l'exécution", verbose_name='Données de sortie')),
                ('context', models.JSONField(default=dict, help_text="Variables et état durant l'exécution", verbose_name='Contexte')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('error_details', models.JSONField(blank=True, default=dict, verbose_name="Détails de l'erreur")),
                ('current_step_id', models.CharField(blank=True, max_length=100, verbose_name='Étape actuelle')),
                ('completed_steps', models.JSONField(default=list, verbose_name='Étapes complétées')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automation.trigger', verbose_name='Déclencheur')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_executions', to=settings.AUTH_USER_MODEL, verbose_name='Déclenché par')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Exécution de Workflow',
                'verbose_name_plural': 'Exécutions de Workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'étape")),
                ('step_id', models.CharField(help_text="Identifiant unique pour référencer l'étape", max_length=100, verbose_name='Identifiant unique')),
                ('action_type', models.CharField(choices=[('validate_data', 'Validation de données'), ('database_save', 'Sauvegarde en base'), ('database_query', 'Requête base de données'), ('integration_call', "Appel d'intégration"), ('send_email', "Envoi d'email"), ('send_webhook', 'Envoi de webhook'), ('transform_data', 'Transformation de données'), ('conditional', 'Condition'), ('loop', 'Boucle'), ('wait', 'Attente'), ('custom_code', 'Code personnalisé')], max_length=50, verbose_name="Type d'action")),
                ('params', models.JSONField(default=dict, help_text="Paramètres de l'action", verbose_name='Paramètres')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Condition pour exécuter cette étape', verbose_name='Condition')),
                ('on_error', models.CharField(choices=[('stop', 'Arrêter le workflow'), ('continue', 'Continuer'), ('retry', 'Réessayer'), ('goto', 'Aller à une étape')], default='stop', max_length=20, verbose_name="En cas d'erreur")),
                ('retry_count', models.IntegerField(default=3, verbose_name='Nombre de tentatives')),
                ('retry_delay', models.IntegerField(default=60, verbose_name='Délai entre tentatives (secondes)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='automation.integration', verbose_name='Intégration')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Étape de Workflow',
                'verbose_name_plural': 'Étapes de Workflow',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(blank=True, max_length=100, verbose_name="ID de l'étape")),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20, verbose_name='Niveau')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.workflowexecution', verbose_name='Exécution')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='automation.workflowstep', verbose_name='Étape')),
            ],
            options={
                'verbose_name': "Log d'exécution",
                'verbose_name_plural': "Logs d'exécution",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du template')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('data', 'Données'), ('communication', 'Communication'), ('integration', 'Intégration'), ('logic', 'Logique'), ('utility', 'Utilitaire')], max_length=50, verbose_name='Catégorie')),
                ('action_type', models.CharField(max_length=50, verbose_name="Type d'action")),
                ('default_params', models.JSONField(default=dict, verbose_name='Paramètres par défaut')),
                ('param_schema', models.JSONField(default=dict, help_text='JSON Schema pour valider les paramètres', verbose_name='Schéma de validation')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('is_system', models.BooleanField(default=False, verbose_name='Template système')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_templates', to='foundation.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Template d'action",
                'verbose_name_plural': "Templates d'actions",
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_public'], name='automation__categor_c5fe68_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['organization', 'status'], name='automation__organiz_4e996a_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['integration_type'], name='automation__integra_6693fb_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'status'], name='automation__organiz_341340_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['project'], name='automation__project_5dba9d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['created_at'], name='automation__created_7ea2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['workflow', 'trigger_type'], name='automation__workflo_9adfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['event_type'], name='automation__event_t_c1ae0c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', 'status'], name='automation__workflo_2bbb85_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['created_at'], name='automation__created_4c7134_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status', 'created_at'], name='automation__status_9c4ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['workflow', 'order'], name='automation__workflo_e8c099_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_id')},
        ),
        migrations.AddIndex(
            model_name='workflowexecutionlog',
            index=models.Index(fields=['execution', 'created_at'], name='automation__executi_ddb027_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecutionlog',
            index=models.Index(fields=['level'], name='automation__level_8bbfb6_idx'),
        ),
    ]
