# Generated by Django 5.0.6 on 2025-11-22 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecutionlog',
            name='step_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name="ID de l'étape"),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('trigger', 'Déclencheur'), ('action', 'Action'), ('condition', 'Condition'), ('math', 'Math'), ('string', 'String'), ('data', 'Data'), ('api', 'API'), ('email', 'Email')], max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='automation.workflow')),
            ],
            options={
                'unique_together': {('workflow', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_port', models.CharField(default='output', max_length=50)),
                ('target_port', models.CharField(default='input', max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='automation.workflow')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='automation.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='automation.node')),
            ],
            options={
                'unique_together': {('workflow', 'source_node', 'target_node', 'source_port', 'target_port')},
            },
        ),
    ]
