# Generated by Django 5.0.6 on 2025-11-20 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0002_remove_user_role_delete_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('layout', 'Layout'), ('forms', 'Formulaires'), ('content', 'Contenu'), ('navigation', 'Navigation'), ('data', 'Données'), ('media', 'Médias'), ('feedback', 'Feedback'), ('overlay', 'Overlay')], default='content', max_length=50)),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: 'button', 'input')", max_length=100)),
                ('properties', models.JSONField(default=dict, help_text="\n        Définition des propriétés configurables du composant.\n        Format: {\n            'prop_name': {\n                'type': 'string|number|boolean|select|color|action',\n                'label': 'Label affiché',\n                'default': 'valeur par défaut',\n                'required': true/false,\n                'options': ['option1', 'option2'] // pour type select\n            }\n        }\n    ")),
                ('validation_rules', models.JSONField(default=dict, help_text="\n        Règles de validation pour les propriétés.\n        Format: {\n            'prop_name': {\n                'min_length': 1,\n                'max_length': 100,\n                'pattern': 'regex',\n                'custom_validation': 'function_name'\n            }\n        }\n    ")),
                ('default_config', models.JSONField(default=dict, help_text='\n        Configuration par défaut quand le composant est ajouté à une page.\n    ')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Composant',
                'verbose_name_plural': 'Composants',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(help_text="Chemin de l'URL (ex: 'home', 'about')", max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Configuration de la page au format JSON (composants, mise en page, etc.)')),
                ('is_home', models.BooleanField(default=False, help_text="Page d'accueil du projet")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('config', models.JSONField(default=dict, help_text='Configuration spécifique de cette instance de composant', verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='studio.component', verbose_name='Composant')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_instances', to='studio.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Instance de composant',
                'verbose_name_plural': 'Instances de composants',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('schema_name', models.CharField(max_length=63, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='foundation.organization')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='studio.project'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('project', 'route')},
        ),
        migrations.CreateModel(
            name='EditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('page', 'Page'), ('component', 'Composant'), ('schema', 'Schéma de données'), ('project', 'Projet')], max_length=20, verbose_name="Type d'élément")),
                ('element_id', models.CharField(max_length=255, verbose_name="ID de l'élément")),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Verrouillé le')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Verrou automatiquement libéré après cette date', null=True, verbose_name='Expire le')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informations supplémentaires sur le verrou', verbose_name='Métadonnées')),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_locks', to=settings.AUTH_USER_MODEL, verbose_name='Verrouillé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_locks', to='studio.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': "Verrou d'édition",
                'verbose_name_plural': "Verrous d'édition",
                'db_table': 'studio_edit_lock',
                'ordering': ['-locked_at'],
                'indexes': [models.Index(fields=['project', 'element_type', 'element_id'], name='studio_edit_project_6a4c66_idx'), models.Index(fields=['locked_by'], name='studio_edit_locked__5bb3fa_idx'), models.Index(fields=['locked_at'], name='studio_edit_locked__8cf9c9_idx')],
                'unique_together': {('project', 'element_type', 'element_id')},
            },
        ),
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.SlugField(max_length=63)),
                ('display_name', models.CharField(max_length=255)),
                ('fields_config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='studio.project')),
            ],
            options={
                'verbose_name': 'Schéma de données',
                'verbose_name_plural': 'Schémas de données',
                'ordering': ['created_at'],
                'unique_together': {('project', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='CollaborationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarré le')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('channel_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du canal WebSocket')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informations sur la session (navigateur, IP, etc.)', verbose_name='Métadonnées')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_sessions', to='studio.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Session de collaboration',
                'verbose_name_plural': 'Sessions de collaboration',
                'db_table': 'studio_collaboration_session',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='studio_coll_project_037ccb_idx'), models.Index(fields=['user', 'is_active'], name='studio_coll_user_id_896a77_idx'), models.Index(fields=['last_activity'], name='studio_coll_last_ac_f43b4c_idx')],
            },
        ),
    ]
