# Generated by Django 5.0.6 on 2025-12-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('DataSchema', 'Table'),
        migrations.RenameModel('FieldSchema', 'Attribute'),
    ]
