# Generated by Django 5.0.6 on 2025-11-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('layout', 'Layout'), ('forms', 'Formulaires'), ('content', 'Contenu'), ('navigation', 'Navigation'), ('data', 'Données'), ('media', 'Médias'), ('feedback', 'Feedback'), ('overlay', 'Overlay')], default='content', max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='default_config',
            field=models.JSONField(default=dict, help_text='\n        Configuration par défaut quand le composant est ajouté à une page.\n    '),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='component',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom de l'icône (ex: 'button', 'input')", max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='properties',
            field=models.JSONField(default=dict, help_text="\n        Définition des propriétés configurables du composant.\n        Format: {\n            'prop_name': {\n                'type': 'string|number|boolean|select|color|action',\n                'label': 'Label affiché',\n                'default': 'valeur par défaut',\n                'required': true/false,\n                'options': ['option1', 'option2'] // pour type select\n            }\n        }\n    "),
        ),
        migrations.AlterField(
            model_name='component',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='validation_rules',
            field=models.JSONField(default=dict, help_text="\n        Règles de validation pour les propriétés.\n        Format: {\n            'prop_name': {\n                'min_length': 1,\n                'max_length': 100,\n                'pattern': 'regex',\n                'custom_validation': 'function_name'\n            }\n        }\n    "),
        ),
        migrations.AlterField(
            model_name='component',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
    ]
