# Generated by Django 5.0.6 on 2025-12-23 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_rename_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationsession',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='componentinstance',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='editlock',
            options={'ordering': ['-locked_at']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='collaborationsession',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='collaborationsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collaborationsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collaborationsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='collaborationsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_sessions', to='studio.project'),
        ),
        migrations.AlterField(
            model_name='collaborationsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='collaborationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='component',
            name='default_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='component',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='properties',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='component',
            name='validation_rules',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='studio.component'),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='linked_field_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_instances', to='studio.attribute'),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='needs_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_instances', to='studio.page'),
        ),
        migrations.AlterField(
            model_name='editlock',
            name='element_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='editlock',
            name='element_type',
            field=models.CharField(choices=[('page', 'Page'), ('component', 'Composant'), ('schema', 'Schéma de données'), ('project', 'Projet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='editlock',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editlock',
            name='locked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='editlock',
            name='locked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='editlock',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='editlock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_locks', to='studio.project'),
        ),
        migrations.AlterField(
            model_name='page',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='route',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='table',
            name='auto_generate_pages',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='schema_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='studio_fieldschema',
        ),
        migrations.AlterModelTable(
            name='component',
            table='studio_component',
        ),
        migrations.AlterModelTable(
            name='componentinstance',
            table='studio_componentinstance',
        ),
        migrations.AlterModelTable(
            name='page',
            table='studio_page',
        ),
        migrations.AlterModelTable(
            name='project',
            table='studio_project',
        ),
        migrations.AlterModelTable(
            name='table',
            table='studio_dataschema',
        ),
    ]
