# Generated by Django 5.0.6 on 2025-11-25 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_component_category_alter_component_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschema',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='icon',
            field=models.CharField(default='📋', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='fields_config',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT_SHORT', 'Texte court (max 255 caractères)'), ('TEXT_LONG', 'Texte long (illimité)'), ('NUMBER_INT', 'Nombre entier'), ('NUMBER_DECIMAL', 'Nombre décimal'), ('DATE', 'Date'), ('DATETIME', 'Date et heure'), ('TIME', 'Heure'), ('BOOLEAN', 'Vrai/Faux'), ('EMAIL', 'Adresse email'), ('URL', 'Lien web'), ('PHONE', 'Numéro de téléphone'), ('COLOR', 'Couleur'), ('FILE', 'Fichier'), ('IMAGE', 'Image'), ('CHOICE_SINGLE', 'Choix unique (liste déroulante)'), ('CHOICE_MULTIPLE', 'Choix multiples (cases à cocher)'), ('RELATION_ONE_TO_ONE', 'Relation 1:1 avec autre table'), ('RELATION_ONE_TO_MANY', 'Relation 1:N avec autre table'), ('RELATION_MANY_TO_MANY', 'Relation N:N avec autre table')], max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('regex_pattern', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='studio.dataschema')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='studio.dataschema')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('schema', 'name')},
            },
        ),
    ]
