# Generated by Django 5.0.6 on 2025-12-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_collaborationsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstance',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Composant parent (pour layout imbriqué)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='studio.componentinstance'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='position',
            field=models.JSONField(blank=True, default=dict, help_text='Position/layout libre: {x,y,w,h,breakpoints,...}'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='slot',
            field=models.CharField(blank=True, default='', help_text='Slot/zone dans le parent (ex: header, content, left, right)', max_length=100),
        ),
    ]
