# Generated by Django 5.0.6 on 2025-11-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_dataschema_description_dataschema_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldschema',
            options={'ordering': ['schema', 'order']},
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Indique si ce composant a été généré automatiquement'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='linked_field_schema',
            field=models.ForeignKey(blank=True, help_text='Champ du schéma lié à ce composant (pour auto-génération)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_instances', to='studio.fieldschema', verbose_name='Schéma de champ lié'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='needs_sync',
            field=models.BooleanField(default=False, help_text='Indique si ce composant nécessite une synchronisation avec le schéma'),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='auto_generate_pages',
            field=models.BooleanField(default=True, help_text='Génère automatiquement les pages (liste, détail, formulaire) lors de la création'),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Dernière synchronisation avec les composants', null=True),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='schema_version',
            field=models.IntegerField(default=1, help_text='Version du schéma pour le suivi des modifications'),
        ),
    ]
