# Generated by Django 5.0.6 on 2025-11-20 19:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('foundation', '0002_remove_user_role_delete_event'),
        ('runtime', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('cpu.usage', 'Utilisation CPU (%)'), ('memory.usage', 'Utilisation mémoire (%)'), ('disk.usage', 'Utilisation disque (%)'), ('network.in', 'Trafic réseau entrant (bytes/s)'), ('network.out', 'Trafic réseau sortant (bytes/s)'), ('requests.count', 'Nombre de requêtes'), ('requests.latency', 'Latence des requêtes (ms)'), ('errors.count', "Nombre d'erreurs"), ('active.users', 'Utilisateurs actifs'), ('database.connections', 'Connexions base de données'), ('cache.hit_rate', 'Taux de succès cache (%)')], max_length=50, verbose_name='Type de métrique')),
                ('value', models.FloatField(verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='Étiquettes')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name="Nom d'hôte")),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Métrique système',
                'verbose_name_plural': 'Métriques système',
                'db_table': 'insights_system_metric',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metric_type', 'created_at'], name='insights_sy_metric__4e96bb_idx'), models.Index(fields=['hostname', 'service'], name='insights_sy_hostnam_b39116_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('response.time', 'Temps de réponse (ms)'), ('requests.count', 'Nombre de requêtes'), ('errors.count', "Nombre d'erreurs"), ('uptime', 'Disponibilité (%)'), ('cpu.usage', 'Utilisation CPU (%)'), ('memory.usage', 'Utilisation mémoire (%)'), ('users.active', 'Utilisateurs actifs'), ('api.calls', 'Appels API'), ('database.queries', 'Requêtes base de données')], max_length=50, verbose_name='Type de métrique')),
                ('value', models.FloatField(verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('environment', models.CharField(default='production', max_length=50, verbose_name='Environnement')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='runtime.generatedapp', verbose_name='Application')),
            ],
            options={
                'verbose_name': "Métrique d'application",
                'verbose_name_plural': "Métriques d'application",
                'db_table': 'insights_application_metric',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', 'created_at'], name='insights_ap_app_id_da6398_idx'), models.Index(fields=['metric_type', 'created_at'], name='insights_ap_metric__e25767_idx'), models.Index(fields=['environment', 'created_at'], name='insights_ap_environ_2d00b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('frontend', 'Interface utilisateur'), ('backend', 'Serveur backend'), ('database', 'Base de données'), ('external', 'Services externes'), ('network', 'Réseau')], max_length=20, verbose_name='Catégorie')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la métrique')),
                ('value', models.FloatField(verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='foundation.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_metrics', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Métrique de performance',
                'verbose_name_plural': 'Métriques de performance',
                'db_table': 'insights_performance_metric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'timestamp'], name='insights_pe_categor_be6846_idx'), models.Index(fields=['name', 'timestamp'], name='insights_pe_name_e2eebe_idx'), models.Index(fields=['organization', 'timestamp'], name='insights_pe_organiz_2e0db1_idx'), models.Index(fields=['user', 'timestamp'], name='insights_pe_user_id_378bf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('user.login', 'Connexion utilisateur'), ('user.logout', 'Déconnexion utilisateur'), ('user.register', 'Inscription utilisateur'), ('user.profile_update', 'Mise à jour profil'), ('project.created', 'Création de projet'), ('project.updated', 'Modification de projet'), ('project.deleted', 'Suppression de projet'), ('project.shared', 'Partage de projet'), ('app.created', "Création d'application"), ('app.updated', "Modification d'application"), ('app.deployed', "Déploiement d'application"), ('app.deleted', "Suppression d'application"), ('workflow.created', 'Création de workflow'), ('workflow.executed', 'Exécution de workflow'), ('workflow.failed', 'Échec de workflow'), ('integration.created', "Création d'intégration"), ('integration.updated', "Modification d'intégration"), ('integration.failed', "Échec d'intégration"), ('security.permission_changed', 'Changement de permissions'), ('security.password_changed', 'Changement de mot de passe'), ('security.2fa_enabled', '2FA activée'), ('security.2fa_disabled', '2FA désactivée'), ('system.backup', 'Sauvegarde système'), ('system.maintenance', 'Maintenance système'), ('system.error', 'Erreur système')], max_length=50, verbose_name="Type d'activité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, max_length=255, verbose_name='ID de session')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='foundation.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateur',
                'db_table': 'insights_user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='insights_us_user_id_552cb8_idx'), models.Index(fields=['organization', 'created_at'], name='insights_us_organiz_c3645c_idx'), models.Index(fields=['activity_type', 'created_at'], name='insights_us_activit_a1bc49_idx'), models.Index(fields=['content_type', 'object_id'], name='insights_us_content_ed2c54_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('session.duration', 'Durée de session (minutes)'), ('pages.visited', 'Pages visitées'), ('actions.performed', 'Actions effectuées'), ('projects.created', 'Projets créés'), ('apps.deployed', 'Applications déployées'), ('time.spent', 'Temps passé (heures)'), ('features.used', 'Fonctionnalités utilisées')], max_length=50, verbose_name='Type de métrique')),
                ('value', models.FloatField(verbose_name='Valeur')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Contexte')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_metrics', to='foundation.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Métrique utilisateur',
                'verbose_name_plural': 'Métriques utilisateur',
                'db_table': 'insights_user_metric',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='insights_us_user_id_204185_idx'), models.Index(fields=['organization', 'date'], name='insights_us_organiz_844e48_idx'), models.Index(fields=['metric_type', 'date'], name='insights_us_metric__43f571_idx')],
                'unique_together': {('user', 'metric_type', 'date')},
            },
        ),
    ]
